name: TradeCycler
version: "${version}"
api-version: '1.21.4'
authors: [ S42, Tamikaschu ]
description: Cycles villager trades when pressed a configured button.
main: tr.s42.tradecycler.TradeCyclerPlugin