[versions]
jvm = "2.0.21"

# Dependencies
paper = "1.21.4-R0.1-SNAPSHOT"
spigot = "1.21.4-R0.1-SNAPSHOT"

[libraries]
stdlib = { group = "org.jetbrains.kotlin", name = "kotlin-stdlib", version.ref = "jvm" }
paper = { group = "io.papermc.paper", name = "paper-api", version.ref = "paper" }
spigot = { group = "org.spigotmc", name = "spigot-api", version.ref = "spigot" }
