name: Release

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Build with Gradle
        run: ./gradlew build

      - name: Get latest tag
        id: get_latest_tag
        run: |
          latest_tag=$(git tag -l 'v*' | sort -V | tail -n1)
          if [ -z "$latest_tag" ]; then
            echo "version=v1.0" >> $GITHUB_OUTPUT
          else
            current_version=$(echo $latest_tag | sed 's/v//')
            next_version=$(echo $current_version | awk -F. '{print $1"."$2+1}')
            echo "version=v$next_version" >> $GITHUB_OUTPUT
          fi

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.get_latest_tag.outputs.version }}
          name: Release ${{ steps.get_latest_tag.outputs.version }}
          draft: true
          body: |
            # CHANGELOG ${{ steps.get_latest_tag.outputs.version }}
            
            ## BUGS:
            -
            -
            
            ## FEATURES:
            -
            -
            
            ## CONTRIBUTERS:
            -
            -
          files: |
            build/libs/*.jar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}